//Existing Chips
Null_Text = "No text#for now"

Cannon_Text = "Cannon to#attack#1 enemy"
AirShot_Text = "Knock#enmy back#1 square"
Vulcan1_Text = "3-shot to#pierce 1#pnael!"
Vulcan2_Text = "4-shot to#pierce 1#pnael!"
Vulcan3_Text = "5-shot to#pierce 1#pnael!"
SuperVulcan_Text = "10-shot to#pierce 1#pnael!"
MiniBomb_Text = "Throws a#MiniBomb#3sq ahead"
Sword_Text = "Cuts enmy#in front!#Range: 1"
WideSword_Text = "Cuts enmy#in front!#Range: 3"
LongSword_Text = "Cuts enmy#in front!#Range: 2"
FireSword_Text = "Cuts enmy#3sq fwrd#w/fire"
AquaSword_Text = "Cuts enmy#3sq fwrd#w/aqua"
ElecSword_Text = "Cuts enmy#3sq fwrd#w/elec"
BambooSword_Text = "Cuts enmy#3sq fwrd#w/wood"
AirSword_Text = "Wide swrd#with air#attack!"
BusterUp_Text = "Power#goes up#by 1"
HP10_Text = "Recovers#10HP"
HP30_Text = "Recovers#30HP"
HP50_Text = "Recovers#50HP"
AreaGrab_Text = "Steals#left edge#from enmy"
Attack10_Text = "+10 for#selected#atk chip"
ShotGun_Text = "Explodes 1#square#behind"
VGun_Text = "Explodes 2#diag.#squares"
LineGun_Text = "Explodes#up,down#on hit"
Spreader_Text = "Creates a#large#explosion"
StepSword_Text = "2 steps,#then uses#wide swrd"
StepCross_Text = "2 steps,#then uses#cross atk"
Invis_Text = "Invisible#for a#while"
StoneBody_Text = "Avoid all#damage w/#stone bdy"
YoYo_Text = "Yoyo atk#reaches#3sq ahead"
GutPunch_Text = "Launches#GutPunch#ahead"
FolderBack_Text = "Restores#all chips#in folder"
Barrier_Text = "Nullifies#10HP of#damage!"

Roll_Text = "Attacks#enmy, then#heals you"
GutsMan_Text = "Sneaks up#to smash#panels!"
CrashMan_Text = "Attacks#enmy w/#big drill"

//New Chips
Reprogram_Text = "Increase#your max#draw by 1"
TimeMachine_Text = "Go back#in time"
Fusion_Text = "Combine#2 chips"
WonderWand_Text = "ChrgAtk#becomes#WonderWand"
SwordMode_Text = "ChrgAtk#becomes#Sword"
BlastShot_Text = "Fires a#giant#cannon"



