globalvar Test_Deck;
Test_Deck = ds_list_create()
ds_list_add(Test_Deck,
Chip_Deck[0],
Chip_Deck[1],
Chip_Deck[2],
Chip_Deck[3],
Chip_Deck[4],
Chip_Deck[5],
Chip_Deck[6],
Chip_Deck[7],
Chip_Deck[8],
Chip_Deck[9],
Chip_Deck[10],
Chip_Deck[11],
Chip_Deck[12],
Chip_Deck[13],
Chip_Deck[14],
)
ds_list_add(Test_Deck,
Chip_Deck[15],
Chip_Deck[16],
Chip_Deck[17],
Chip_Deck[18],
Chip_Deck[19],
Chip_Deck[20],
Chip_Deck[21],
Chip_Deck[22],
Chip_Deck[23],
Chip_Deck[24],
Chip_Deck[25],
Chip_Deck[26],
Chip_Deck[27],
Chip_Deck[28],
Chip_Deck[29],
)

