globalvar Test_Deck;
Test_Deck = ds_list_create()
ds_list_add(Test_Deck,
obj_firesword_w,
obj_aquasword_w,
obj_elecsword_w,
obj_wonderwand_m,
obj_swordmode_star,
obj_minibomb_a,
obj_minibomb_b,
obj_airshot_star,
obj_airshot_star,
obj_sword_s,
obj_sword_s,
obj_sword_s,
obj_widesword_s,
obj_widesword_s,
obj_airshot_star,
)
ds_list_add(Test_Deck,
obj_vulcan_n,
obj_vulcan_n,
obj_busterup_star,
obj_reprogram_n,
obj_areagrab_s,
obj_reprogram_n,
obj_areagrab_s,
obj_hp10_star,
obj_hp10_star,
obj_hp10_star,
obj_stonebody_k,
obj_hp10_star,
obj_airsword_star,
obj_roll_r,
obj_stonebody_k,
)

